### ISSUE TITLE
Doesn't work after suspend

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/dde-polkit-agent#2]
I don't really know exactly whether this belongs here.

Using DDE on Arch. After suspend and resume pamac is not able to authorize me anymore and that seems to be somehow related to polkit not working correctly anymore.

I already started systemctl restart of polkit.service which did not work.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
