### ISSUE TITLE
Abnormal cpu usage after resume

### ISSUE THREAD

**Issue by alsoGAMER** [linuxdeepin/dde-polkit-agent#21]
I don't know what the cause of this problem is, the weirdness is that it all solves itself by simply killing it and waiting for it to self-restart

I'm using manjaro 18.0.4 x64 with dde 15.10

**Comment by BLumia** [comment]
cc @justforlxz

**Comment by jeffgoh** [comment]
happens to me on fedora 31 with deepin-polkit-agent-5.0.0-1.fc31.x86_64 - which seems to be deepin-desktop-base-2019.07.10
